# https://docs.clusterhq.com/en/1.4.0/labs/compose.html

rabbitblackl:
  build: rabbitmq_mqtt/
  environment:
    RABBITMQ_NODENAME: rabbitblack
  hostname: rabbit_black
  ports:
    - "5673:5672"
    - "15673:15672"
    - "25673:25672"

rabbitred:
  build: rabbitmq_mqtt/
  environment:
    RABBITMQ_NODENAME: rabbitred
  hostname: rabbit_red
  ports:
    - "5674:5672"
    - "15674:15672"
    - "25674:25672"
    - "1234:1234/udp"

rabbitinternal:
  build: rabbitmq_mqtt/
  environment:
    RABBITMQ_NODENAME: rabbitinternal
  hostname: rabbit_internal
  ports:
    - "5675:5672"
    - "15675:15672"
    - "25675:25672"
    - "1234:1234/udp"
